name: VNSkyblock
version: '${project.version}'
main: me.tony.main.vnskyblock.VNSkyblock
api-version: '1.21'
softdepend: [Essentials, Citizens]


commands:
  voltadmincontrol:
    aliases:
      - vac
      - vr
    description: Volt Skyblock Admin General Commands.
  isdelete:
    aliases:
      - isd
      - isr
      - isremove
    description: Delete your island
  vault:
    aliases:
      - v
    description: View your vault
  bal:
    aliases:
      - balance
      - b
    description: Check your Balance
  gem:
    description: Gem Control
  petadmin:
    description: Pet Administrator Commands
    aliases:
      - pa
      - padmin
      - peta
  pet:
    description: Pet Main Command
    aliases:
      - p
  tag:
    description: Set a Tag
    aliases:
      - t
  leveladmin:
    description: Level Management
    aliases:
      - la
      - l
  backpack:
    description: Backpack
    aliases:
      - bp
      - b
      - storage
  setspawn:
    description: Set spawn
  spawn:
    description: Teleport to spawn
  customitem:
    description: Give yourself custom items
    aliases:
      - ci
      - i
      - item
  minion:
    description: General Minion Command
    aliases:
      - m